// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PostTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void postTest() {
    driver.get("https://www.fl.ru/");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.cssSelector(".container > .align-items-center")).click();
    driver.findElement(By.linkText("Разместить заказ")).click();
    driver.findElement(By.linkText("Опубликовать заказ")).click();
    driver.findElement(By.id("ui-input-project-title-input")).click();
    driver.findElement(By.id("ui-input-project-title-input")).sendKeys("1234");
    driver.findElement(By.cssSelector(".wizard__wrapper")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".ui-system__message"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("ui-input-project-title-input")).click();
    driver.findElement(By.id("ui-input-project-title-input")).sendKeys("123456");
    driver.findElement(By.id("qa-project-wizard-step-1-button-next")).click();
    {
      WebElement element = driver.findElement(By.id("qa-project-wizard-step-1-button-next"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".text-danger > div"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".ui-textarea")).click();
    driver.findElement(By.cssSelector(".ui-textarea")).sendKeys("5432");
    driver.findElement(By.cssSelector(".mt-36 .text-5")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".ui-system__message"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".ui-textarea")).click();
    driver.findElement(By.cssSelector(".ui-textarea")).sendKeys("54321");
    driver.findElement(By.id("qa-project-wizard-step-1-button-next")).click();
    driver.findElement(By.id("ui-input-project-order-budget-input")).click();
    driver.findElement(By.id("ui-input-project-order-budget-input")).sendKeys("1200");
    driver.findElement(By.id("date-picker")).click();
    driver.findElement(By.cssSelector(".id-2024-05-31 > .vc-day-content")).click();
    driver.findElement(By.id("qa-project-wizard-step-2-button-next")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".text-3:nth-child(1)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("qa-project-wizard-step-3-button-next")).click();
    {
      WebElement element = driver.findElement(By.id("qa-project-wizard-step-3-button-next"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".mt-36 > div"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".mb-16 .text-6:nth-child(4) > .read-more-trigger")).click();
    driver.findElement(By.cssSelector(".list-unstyled:nth-child(3) .ui-radio-label")).click();
    driver.findElement(By.id("qa-project-wizard-step-3-button-next")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("qa-sign-in-button"));
      assert(elements.size() > 0);
    }
  }
}
